### ISSUE TITLE
Android 0.9.2 can't connect

### ISSUE THREAD

**Issue by Heclalava** [KomodoPlatform/komodo-wallet-mobile#155]
LineageOS 21, rooted, Google certified. Tried a variety of VPN servers. Tried to reinstall, clear app data. No luck. Stuck here:
![Screenshot_20240809-173956_Trebuchet](https://github.com/user-attachments/assets/7e14ed21-f2ed-44d0-94ad-9a16dca0c09c)

**Comment by Heclalava** [comment]
Further update to this the desktop wallet (Linux app image) has no issues connecting.
![image](https://github.com/user-attachments/assets/ea522da6-a443-4431-9728-c9613900bf8c)
So it isn't VPN related, as both Android and Linux run through the same VPN server in my router. 
Could it be related to widevine security level? Lineage OS 21 only has level 3 security

**Comment by Generalresolution03** [comment]
Hello @Heclalava 
This is a reoccurring issue, have you been able to resolve yet?

**Comment by Heclalava** [comment]
> Hello @Heclalava This is a reoccurring issue, have you been able to resolve yet?

It seemed to have resolved itself without me doing anything. 

However as I use the wallet on my desktop mostly, I recently uninstalled the mobile wallet as I can remote into my desktop from my phone to control the wallet there if needed.

**Comment by Generalresolution03** [comment]
kindly close this issue then.
thanks
