### ISSUE TITLE
Add faucet buttons for DOC/MARTY

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet-mobile#34]
DOC/MARTY have been added to the faucet API at https://faucet.komodo.earth/docs
All supported coins: `DOC RICK MARTY MORTY ZOMBIE`
Faucet node also maintains maker orders for all pair combinations of the above.

**Comment by CharlVS** [comment]
Addressed as part of upcoming #31

**Comment by kivqa** [comment]
@CharlVS Faucets for Doc/Marty and Zombie are working. We can close this issue

**Comment by kivqa** [comment]
Faucets work as expected.
