### ISSUE TITLE
Missing Git Tag & Github release for version 0.9.0 on Google Play

### ISSUE THREAD

**Issue by emanuelb** [KomodoPlatform/komodo-wallet-mobile#60]
On Google Play the version is 0.6.5 https://play.google.com/store/apps/details?id=com.komodoplatform.atomicdex

With details: Version: 0.6.5 Updated on: Jun 22, 2023 Released on: Dec 15, 2022

While the latest git tag in repo is v0.6.4-1 from Jun 12 and the latest github release is for version 0.6.4 that match the v0.6.4-1 tag
https://github.com/KomodoPlatform/komodo-wallet-mobile/releases/tag/v0.6.4-1

Fix:
git tag the version 0.6.5 and make a Github release for it as well, to match the version on Google Play.

The commit that match 0.6.5 release is likely https://github.com/KomodoPlatform/komodo-wallet-mobile/commit/c8075541c7ccf285eced81693dbeb03973815b55 or the 2 commit before it https://github.com/KomodoPlatform/komodo-wallet-mobile/commit/5c1d8fb053afd17ca818c26e54b8200a204320a4 or https://github.com/KomodoPlatform/komodo-wallet-mobile/commit/f4529bd0e324bb16a7c807688a6b6c6582067d80

This issue was opened as part of WalletScrutiny Project https://walletscrutiny.com/ details in related verification issue on WS: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/490#note_1574722812

**Comment by xrviv** [comment]
Half a year later, the Play version is already version 0.9.0. 

We might have to re-label this as not source-available.

**Comment by CharlVS** [comment]
Thanks for bringing this to our attention. The app is fully open source as it has been since first opened to the public but will need to update version tags and add GH release.

**Comment by CharlVS** [comment]
Please see below for the tagged `0.9.0` release. I'm looking into the reported issue about documenting CLI build process this week.

## [`0.9.0` GitHub Release](https://github.com/KomodoPlatform/komodo-wallet-mobile/issues/60)
