### ISSUE TITLE
Failed to activate ZHTLC coins, please try again later

### ISSUE THREAD

**Issue by warelock2** [KomodoPlatform/komodo-wallet-mobile#62]
- Wallet version: 0.7.0 (96) - 1.0.7-beta_
- Platform: Android 13
- OS version: Latest GrapheneOS with full Google Play Services support enabled
- Hardware: Google Pixel 7a
- App store: Google Play Store
---
- Expected behavior: $ARRR synced and activated
- Actual behavior: $ARRR is not synced and activated
- Error message: Failed to activate ZHTLC coins, please try again later
---
- I tried all three options for syncing based on date
- It bombs at 5% sync progress
- I used the "Share Log File" feature, afterwards

**Comment by gcharang** [comment]
other users report the same. Sample of envs: iOS, MIUI 14

**Comment by CharlVS** [comment]
@warelock2 can you please share the log file here? Is this your local build or the app store version?

**Comment by warelock2** [comment]
@CharlVS This is confirmed as working with the new version of the app I just downloaded. Let me know if you still need the logs.

**Comment by warelock2** [comment]
@CharlVS This is confirmed as working with the new version of the app I just downloaded. Let me know if you still need the logs.
